name: ubke-repro
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy=1.26.4
  - scipy=1.11.4
  - pyyaml=6.0.1
  - tqdm=4.66.1
  - pip
  - pip:
      - soundfile==0.12.1
      - pystoi==0.4.1
      - pesq==0.0.4
